--- #YAML:1.0
name:                Net-PJLink
version:             1.00
abstract:            PJLink protocol implementation
license:             perl
author:              
    - Kyle Emmons <kemmons@tma-0.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Digest::MD5:                   0
    Exporter:                      0
    IO::Select:                    0
    IO::Socket::INET:              0
    Switch:                        0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
