# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-PJLink
version:      0.03
version_from: lib/Net/PJLink.pm
installdirs:  site
requires:
    Carp:                          0
    Digest::MD5:                   0
    Exporter:                      0
    IO::Select:                    0
    IO::Socket::INET:              0
    Switch:                        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
