--- #YAML:1.0
name:               Net-PJLink
version:            1.02
abstract:           PJLink protocol implementation
author:
    - Kyle Emmons <kemmons@tma-0.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    Digest::MD5:       0
    Exporter:          0
    IO::Select:        0
    IO::Socket::INET:  0
    Switch:            0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
